info: # Application-Info for the Info-Actuator
  group: "@pom.groupId@"
  artifact: "@pom.artifactId@"
  description: "@pom.description@"
  version: "@pom.version@"
  name: "@pom.name@"
  spring-boot: "@spring-boot.version@"
  spring-cloud: "@spring-cloud.version@"
  # Tags for the Spring Boot Admin UI
  tags:
    version: "@pom.version@"
    spring-boot: "@spring-boot.version@"
    spring-cloud: "@spring-cloud.version@"

project:
  parent:
    module: "@project-parent.name@"

module: "${AnsiColor.MAGENTA} :: ${AnsiStyle.BOLD}${project.parent.module} ::${AnsiColor.CYAN}"
title1: "${AnsiColor.BLUE}${AnsiStyle.BOLD}    App Info    ${AnsiStyle.NORMAL}${AnsiColor.CYAN}"
txt1: "${AnsiColor.YELLOW}Project:${AnsiStyle.NORMAL} ${spring.application.name}${AnsiColor.CYAN}"
txt2: "${AnsiColor.YELLOW}Version:${AnsiStyle.NORMAL} ${info.version}${AnsiColor.CYAN}"
txt3: "${AnsiColor.YELLOW}Description:${AnsiStyle.NORMAL} ${info.description}${AnsiColor.CYAN}"
