version: '3'

services:
#  config-server:
#    image: mgridah/orange-care-config
#    container_name: config-server
#    deploy:
#      resources:
#        limits:
#          memory: 512M
#    healthcheck:
#      test: ["CMD", "curl", "-I", "http://config-server:8888"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#    ports:
#      - "8888:8888"

  discovery-server:
    image: mgridah/orange-care-registry
    container_name: orange-discovery-server
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - 8761:8761

