spring:
  application:
    name: "@pom.artifactId@"
  profiles:
    active:
      - secure
      - info
      - default
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
      - application-info.yml

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://orange-care-config:8888
