<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.billcom</groupId>
        <artifactId>orange-care-security-build</artifactId>
        <version>${revision}</version>
        <relativePath>../orange-care-security-build</relativePath>
    </parent>

    <artifactId>orange-care-security-spring-boot-starter</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.billcom</groupId>
            <artifactId>orange-care-security-connection-pools</artifactId>
        </dependency>
        <dependency>
            <groupId>com.billcom</groupId>
            <artifactId>orange-care-security-beans</artifactId>
        </dependency>
    </dependencies>
    
</project>
