<?xml version="1.0" encoding="UTF-8"?>
<!--  Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Metro/2.2-b13 (branches/2.2-6964; 2012-01-09T18:04:18+0000) JAXWS-RI/2.2.6-promoted-b20 JAXWS/2.2 svn-revision#unknown.  -->
<xs:schema xmlns:tns="http://ApiNotificationSMSWs.ws.dsi.orange.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" targetNamespace="http://ApiNotificationSMSWs.ws.dsi.orange.com">
  <xs:complexType name="sendNotificationResponse">
    <xs:complexContent>
      <xs:extension base="tns:baseWSResponse">
        <xs:sequence>
          <xs:element name="msisdn" type="xs:string" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="baseWSResponse" abstract="true">
    <xs:sequence>
      <xs:element name="comment" type="xs:string" minOccurs="0"/>
      <xs:element name="errorCode" type="xs:string" minOccurs="0"/>
      <xs:element name="isSuccessful" type="xs:boolean" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>