server:
  port: 8080

spring:
  application:
    name: "@project.artifactId@"
  profiles:
    active: info
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
