##############################################################
#                  CONFIGURATION IMPORT                      #
##############################################################

spring.config.import=config/connection-pools.yml,config/connection-settings.yml
spring.output.ansi.enabled=always

spring.application.name=@project.artifactId@

server.port=0

##############################################################
#                  Swagger CONFIGURATION                     #
##############################################################

##############################################################
#                  Swagger CONFIGURATION                     #
##############################################################
modulename=BscsWs
module=${AnsiColor.MAGENTA} :: ${AnsiStyle.BOLD}${modulename} ::${AnsiColor.CYAN}
title1=${AnsiColor.BLUE}${AnsiStyle.BOLD}    App Info    ${AnsiStyle.NORMAL}${AnsiColor.CYAN}
txt1=${AnsiColor.YELLOW}Project:${AnsiStyle.NORMAL} ${application.title}${AnsiColor.CYAN}
txt2=${AnsiColor.YELLOW}Version:${AnsiStyle.NORMAL} ${application.version}${AnsiColor.CYAN}




