##############################################################
#                   Application Settings                     #
##############################################################

# This parameter indicates to automatic-retry in case the cms object failed to execute some commands
# When it is "0" then no automatic re-try, which means if the execution fails then it will through an exception;
# Otherwise, the positive value indicates to the number of the automatic retries.
app.automatic-retry-number=3

# duration in hours of validity for the passwords in cache
app.cache-validity-hours=1


##############################################################
#                    CMS CONFIGURATION                       #
##############################################################

# Soi Name
app.soi-name=CIL

# SOi Version
app.soi-version=7

# CMS ServerName
app.server-name=com/lhs/public/soi/fedfactory1

