##############################################################
#                  ServerConnectionPools                     #
##############################################################


#############################
#                           #
# ServerConnectionPoolNames #
#                           #
#############################

#Default Connection Pool Name
default.connection.default-connection-user=ADMX
#Active Connection Pool Names
server.pools.config.connection-pool-names=ADMX,SOICS
#############################
#                           #
#    DefaultPoolSettings    #
#                           #
#############################


#time out in seconds
default.pool.connection-time-out=100
#Maximum no of connection to be created for the pool
default.pool.max-num-connections=5
#Minimum no of connection to be created when the pool starts
default.pool.min-num-connections=1
#No of attempts to be done by application to get a connection from pool
default.pool.no-of-connection-attempts=3
#Time interval in milli seconds between two successive interval
default.pool.connection-attempt-interval=60


#############################
#                           #
#    ConnectionPoolNames    #
#                           #
#############################


#connection_pool 1
connection.pools[0].bscs-user=ADMX
connection.pools[0].bscs-user-password=ADMX
connection.pools[0].connection-timeout=100
connection.pools[0].max-num-connections=15
connection.pools[0].min-num-connections=3
connection.pools[0].no-of-connection-attempts=3
connection.pools[0].connection-attempt-interval=60

#connection_pool 2
connection.pools[1].bscs-user=SOICS
connection.pools[1].bscs-user-password=SOICS
connection.pools[1].connection-timeout=10
connection.pools[1].max-num-connections=1
connection.pools[1].min-num-connections=1
connection.pools[1].no-of-connection-attempts=3
connection.pools[1].connection-attempt-interval=60


#connection_pool 3
#connection.pools[2].bscs-user=SUPERVISOR1
#connection.pools[2].bscs-user-password=SUPERVISOR1
#connection.pools[2].connection-timeout=100
#connection.pools[2].max-num-connections=10
#connection.pools[2].min-num-connections=1
#connection.pools[2].no-of-connection-attempts=3
#connection.pools[2].connection-attempt-interval=60




