/** Login Configuration for the JaasAuthenticationProvider
 **/

CXContext {
   com.lhs.ccb.cfw.wcs.security.auth.module.SecuritySoiLoginModule required;
};

WSContext {
   com.billcom.connectionpools.utils.CacheAuthenticationProvider required;
};
