spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
      client:
        registration:
          login-client:
            provider: spring
            client-id: eureka-client
            client-secret: eureka-connect
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8761/login/oauth2/code/login-client
            scope: openid,profile
            client-name: Spring
        provider:
          spring:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks
