server:
  port: 8761
spring:
  application: # Application-Info for the Info-Actuator
    name: "@project.artifactId@"
  profiles:
    active:
      - info
      - secure
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
