spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
      client:
        registration:
          eureka-client-oidc:
            provider: spring
            client-id: eureka-client
            client-secret: eureka-connect
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8761/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: eureka-client-oidc
          eureka-client-authorization-code:
            provider: spring
            client-id: eureka-client
            client-secret: eureka-connect
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8761/authorized"
            scope: services.read
            client-name: eureka-client-authorization-code
          eureka-client-client-credentials:
            provider: spring
            client-id: eureka-client
            client-secret: eureka-connect
            authorization-grant-type: client_credentials
            scope: services.read
            client-name: eureka-client-client-credentials
        provider:
          spring:
            issuer-uri: http://localhost:9000
