################################################################
##                 Web Services Configuration                  #
################################################################
#
##############################
##                           #
##  Endpoints Configuration  #
##                           #
##############################
#
#######  Web Services Endpoints  ######
#endpoint.bscs.contract-handling.url=http://192.168.10.54:8080/ContractHandling/services/ContractHandling?wsdl
#endpoint.bscs.contract-handling.username=ADMX
#endpoint.bscs.contract-handling.password=ADMX
#
#endpoint.bscs.customer-handling.url=http://192.168.10.54:8080/ContractHandling/services/ContractHandling?wsdl
#endpoint.bscs.customer-handling.username=ADMX
#endpoint.bscs.customer-handling.password=
#
#endpoint.wsi.financial.allocation.write.url=http://192.168.10.95:13001/wsi/services/ws_CIL_7_FinancialAllocationWriteService.wsdl
#endpoint.wsi.financial.allocation.write.username=ADMX
#endpoint.wsi.financial.allocation.write.password=ADMX
#
#endpoint.wsi.financial.allocation.reverse.url=http://192.168.10.95:13001/wsi/services/ws_CIL_7_FinancialAllocationReverseService.wsdl
#endpoint.wsi.financial.allocation.reverse.username=ADMX
#endpoint.wsi.financial.allocation.reverse.password=ADMX
#
#endpoint.wsi.financial.document.search.url=http://192.168.10.95:13001/wsi/services/ws_CIL_7_FinancialDocumentSearchService.wsdl
#endpoint.wsi.financial.document.search.username=ADMX
#endpoint.wsi.financial.document.search.password=ADMX
#
#endpoint.wsi.financial.document.read.url=http://192.168.10.95:13001/wsi/services/ws_CIL_7_FinancialDocumentReadService.wsdl
#endpoint.wsi.financial.document.read.username=ADMX
#endpoint.wsi.financial.document.read.password=ADMX
#
#endpoint.wsi.financial.document.detail-read.url=http://192.168.10.95:13001/wsi/services/ws_CIL_7_FinancialDocumentDetailReadService.wsdl
#endpoint.wsi.financial.document.detail-read.username=ADMX
#endpoint.wsi.financial.document.detail-read.password=ADMX
#
#
